config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount ShibRack::Engine => '/auth'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'welcome#index'

  get '/welcome' => 'welcome#index'
  get '/documentation' => 'documentation#index'

  resources :snapshots, only: %i[index show] do
    collection do
      get 'latest'
      get 'failed'
    end
  end

  namespace :documentation do
    resources :attributes,
              only: %i[index show],
              id: /[A-Za-z0-9.:\-]+?/,
              format: /json|csv|xml|yaml/
    resources :categories, only: %i[index show]
  end
end

app/controllers/documentation/attributes_controller.rb
# frozen_string_literal: true

module Documentation
  class AttributesController < ApplicationController
    skip_before_action :ensure_authenticated

    before_action :public_action, :subject
    before_action :set_documentation_attribute, only: [:show]

    def index
      @federation_attributes = FederationAttribute.name_ordered.all
    end

    def show
      @attribute_categories = @federation_attribute.categories
                                                   .enabled
                                                   .map do |category|
        [category.name, documentation_category_path(category)]
      end
    end

    private

    def set_documentation_attribute
      id = FederationAttribute.fuzzy_lookup(params[:id]).first.try(:id)

      @federation_attribute = FederationAttribute.find(id)
    end
  end
end

app/controllers/documentation/categories_controller.rb
# frozen_string_literal: true

module Documentation
  class CategoriesController < ApplicationController
    skip_before_action :ensure_authenticated

    before_action :public_action, :subject
    before_action :set_documentation_category, only: [:show]

    def index
      @federation_categories = Category.enabled.order(:order).all
    end

    def show
      @category_attributes = @federation_category
                             .federation_attributes
                             .name_ordered
                             .map do |attribute|
        [
          attribute.primary_alias_name,
          documentation_attribute_path(attribute.oid)
        ]
      end
    end

    private

    def set_documentation_category
      @federation_category = Category.enabled.find(params[:id])
    end
  end
end

app/controllers/documentation_controller.rb
# frozen_string_literal: true

class DocumentationController < ApplicationController
  skip_before_action :ensure_authenticated

  before_action :public_action, :subject

  def index; end
end

app/views/documentation/attributes/index.html.slim
ol.breadcrumb
  li = link_to 'Documentation', documentation_path
  li.active Attributes

table.table
  thead
    tr
      th Primary Alias
      th Other Aliases
      th OID
      th Extra Information
  tbody
    - @federation_attributes.each do |federation_attribute|
      tr
        td = federation_attribute.primary_alias_name
        td = federation_attribute.aliases.count > 0 ? "#{federation_attribute.aliases.map(&:name).join(', ')}" : ''
        td = federation_attribute.oid
        td = link_to "Documentation", documentation_attribute_path(federation_attribute.oid)

app/views/documentation/attributes/show.html.slim
ol.breadcrumb
  li = link_to 'Documentation', documentation_path
  li = link_to 'Attributes', documentation_attributes_path
  li.active = @federation_attribute.primary_alias_name

dl.dl-horizontal
  dt Name
  dd = @federation_attribute.primary_alias_name

  - if @federation_attribute.aliases.count > 0
    dt Aliases
    dd
      - if @federation_attribute.aliases.count > 1
        ul
          - @federation_attribute.aliases.map do |a|
            li = a.name
      - else
        = @federation_attribute.aliases.first.name

  dt Categories
  dd
    - if @federation_attribute.aliases.count > 1
      ul
        - @attribute_categories.map do |name, path|
          li == link_to(name, path)
    - else
      - @attribute_categories.map do |name, path|
        == link_to(name, path)

  br

  dt Number of values
  dd = @federation_attribute.singular ? 'One' : 'One or more'

  dt Description
  dd == @federation_attribute.description

  - if @federation_attribute.notes_on_format?
    br

    dt Format
    dd == @federation_attribute.notes_on_format

  - if @federation_attribute.notes_on_usage?
    br

    dt Notes on usage
    dd == @federation_attribute.notes_on_usage

  - if @federation_attribute.notes_on_privacy?
    br

    dt Notes on privacy
    dd == @federation_attribute.notes_on_privacy