config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount ShibRack::Engine => '/auth'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'welcome#index'

  get '/welcome' => 'welcome#index'
  get '/documentation' => 'documentation#index'

  resources :snapshots, only: %i[index show] do
    collection do
      get 'latest'
      get 'failed'
    end
  end

  namespace :documentation do
    resources :attributes,
              only: %i[index show],
              id: /[A-Za-z0-9.:\-]+?/,
              format: /json|csv|xml|yaml/
    resources :categories, only: %i[index show]
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :ensure_authenticated

  def index
    public_action
  end
end

app/views/welcome/index.html.slim
.alert
  h2 Attribute Validator
  p
    | This service will validate the attributes provided about you from your identity provider ensuring they are provided in a format that is suitable for consumption by AAF connected services.

  br
  p
    = link_to latest_snapshots_path, class: 'btn btn-primary btn-lg', role: 'button' do
      i.glyphicon.glyphicon-user>
      | &nbsp;Show me my attributes
    end
  br

.alert
  p
    h5 Identity Provider Administrators

  p
    ' If you're the administrator of an Identity Provider and
    strong
      ' this is the first time
    ' you've accessed this validator please ensure you've
    => link_to 'configured automated attribute release', 'http://support.aaf.edu.au/entries/22545567-Automating-Attribute-Release'
    ' or correctly setup manual attribute release policies for your users before continuing to ensure you don't have connectivity problems with services such as this.

  p
    | If you need further assistance you can
    =<> link_to 'access the online AAF support desk', 'http://support.aaf.edu.au'
    | or alternatively you can
    =< mail_to 'support@aaf.edu.au', 'email AAF support'
    | .