config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount ShibRack::Engine => '/auth'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'welcome#index'

  get '/welcome' => 'welcome#index'
  get '/documentation' => 'documentation#index'

  resources :snapshots, only: %i[index show] do
    collection do
      get 'latest'
      get 'failed'
    end
  end

  namespace :documentation do
    resources :attributes,
              only: %i[index show],
              id: /[A-Za-z0-9.:\-]+?/,
              format: /json|csv|xml|yaml/
    resources :categories, only: %i[index show]
  end
end

app/models/snapshot.rb
# frozen_string_literal: true

class Snapshot < ApplicationRecord
  has_many :snapshot_attribute_values, dependent: :destroy
  has_many :attribute_values,
           through: :snapshot_attribute_values,
           dependent: :destroy,
           inverse_of: false
  belongs_to :subject

  valhammer

  scope :provisioned, lambda {
    includes(snapshot_attribute_values: [:attribute_value])
  }

  def name(explicit_subject = nil)
    explicit_subject ||= subject

    "Snapshot #{number(explicit_subject)}"
  end

  def number(explicit_subject = nil)
    explicit_subject ||= subject

    Snapshot.where(subject: explicit_subject).ids.index(id) + 1
  end

  def latest?(explicit_subject = nil)
    explicit_subject ||= subject

    Snapshot.latest(explicit_subject) == self
  end

  class << self
    def latest(subject)
      subject.snapshots.last
    end

    def create_from_receiver(subject, attrs)
      snapshot = Snapshot.new
      subject.snapshots << snapshot

      snapshot = assign_attributes(attrs, snapshot)
      snapshot.save!

      snapshot
    end

    def assign_attributes(attrs, snapshot)
      FederationAttribute.where(http_header: attrs.keys).find_each do |db_attr|
        parse_attribute_values(db_attr, attrs).each do |value|
          next if value.blank?

          snapshot.attribute_values << AttributeValue.new(
            value: value,
            federation_attribute: db_attr
          )
        end
      end

      snapshot
    end

    def parse_attribute_values(db_attribute, attrs)
      if db_attribute.singular?
        [attrs[db_attribute.http_header]]
      else
        Class.new.extend(ShibRack::AttributeMapping::ClassMethods)
             .parse_multi_value(attrs[db_attribute.http_header])
      end
    end
  end

  # :nocov:
  rails_admin do
    list do
      field :id do
        label 'Internal ID'
      end

      field :name

      field :subject do
        searchable [:name]
        queryable true
      end
    end

    edit do
      field :subject

      field :attribute_values do
        label label.titleize
      end
    end

    show do
      field :name
      field :subject

      field :attribute_values do
        label label.titleize
      end

      field :created_at
      field :updated_at

      fields :created_at, :updated_at do
        label label.titleize
      end
    end
  end

  # :nocov:
end

app/controllers/snapshots_controller.rb
# frozen_string_literal: true

class SnapshotsController < ApplicationController
  before_action :public_action
  skip_before_action :ensure_authenticated, only: [:failed]

  def failed
    return redirect_to(root_path) unless session[:attributes]

    @failed = true
    @snapshot = Snapshot.new(created_at: Time.current)
    @snapshot = Snapshot.assign_attributes(session[:attributes], @snapshot)

    show_actions

    request.env['rack.session'].destroy
  end

  def latest
    eager_load

    @snapshot = @snapshot_scope.where(subject: @subject).last

    show_actions
  end

  def index
    @snapshots = @subject.snapshots.order(id: :desc)
  end

  def show
    eager_load

    @snapshot = @snapshot_scope.find(params[:id])

    @admin_viewer = @subject != @snapshot.subject

    show_actions
  end

  private

  def show_actions
    @attribute_values = @snapshot.attribute_values
    @categories = Category.enabled.order(:order).all

    render :show
  end

  def eager_load
    if subject.permits?('app:validator:admin:web_interface')
      @snapshot_scope = Snapshot.provisioned
    else
      @subject = Subject.includes(:snapshots).find_by(id: session[:subject_id])
      @snapshot_scope = @subject.snapshots.provisioned
    end
  end
end

app/views/snapshots/index.html.slim
h2
  | My Snapshot History

table.table
  thead
    tr
      th Name
      th Taken At
  tbody
    - @snapshots.each do |snapshot|
      tr
        td
          = link_to snapshot.name(snapshot.subject), snapshot_path(snapshot)
        td
          = local_time(snapshot.created_at, :validator_date_format)

app/views/snapshots/show.html.slim
- if @failed
  .alert.alert-warning
    h4
      span.glyphicon.glyphicon-exclamation-sign
      |&nbsp;
      |&nbsp;
      strong Session Halted

    p
      | You've
      strong<> successfully logged in
      | but your organisation has not provided the minimal set of data this application needs to function correctly.
    p This is a backend technical issue and has not been caused by any action you've taken. We're very sorry for the inconvenience.

    p
      | AAF support is available to assist in resolving this error in partnership with technical staff at your organisation.
      | &nbsp; You can reach us via email at
      =< mail_to 'support@aaf.edu.au'

  hr

  .alert.alert-info
    h4
      span.glyphicon.glyphicon-info-sign
      |&nbsp;
      |&nbsp;
      strong Information for Identity Provider administrators

    p The Identity Provider has not supplied the following attributes to this service or they were not supplied in a valid format, preventing this application from functioning correctly.

    h5 Shibboleth IdP 3.0+ or non Shibboleth IdP
    ul
      li
        span
          => link_to 'A persistent SAML NameID', 'https://wiki.shibboleth.net/confluence/display/IDP30/PersistentNameIDGenerationConfiguration'
      li
        span
          =>link_to 'mail', documentation_attribute_path('oid:0.9.2342.19200300.100.1.3')

    h5 Shibboleth IdP 2.x
    ul
      li
        span
          => link_to 'eduPersonTargetedID', documentation_attribute_path('oid:1.3.6.1.4.1.5923.1.1.1.10')
      li
        span
          =>link_to 'mail', documentation_attribute_path('oid:0.9.2342.19200300.100.1.3')
  hr
- else
  h2 = @snapshot.name(@snapshot.subject)
small
  | Taken on #{local_time(@snapshot.created_at, :validator_date_format)}

- unless @failed
  - if @admin_viewer
    .alert.alert-warning role="alert"
      | Note:  This is not your snapshot.  You are viewing this snapshot as an admin.
  - unless @snapshot.latest?(@snapshot.subject)
    .alert.alert-warning role="alert"
      | This is not&nbsp;
      - if @admin_viewer
        = @snapshot.subject.name
        | 's (
        = @snapshot.subject.mail
        | )&nbsp;
      - else
        | your&nbsp;
      | most recent snapshot.
      =< link_to snapshot_path(Snapshot.latest(@snapshot.subject)) do
        | View&nbsp;
        - if @admin_viewer
          | their
        - else
          | your
        | &nbsp;most recent attributes in&nbsp;
        - if @admin_viewer
          | their
        - else
          | your
        | &nbsp;latest snapshot.
  - unless @snapshot.subject.valid_identifier_history?
    .alert.alert-danger role="alert"
      | Warning: Your
      =<> link_to 'auEduPersonSharedToken', documentation_attribute_path('oid:1.3.6.1.4.1.27856.1.2.5'), target: '_blank'
      | is changing over time.

p
  input type="search" id="search" class="form-control hidden-print" placeholder="Search..."

- @categories.each do |category|
  .panel.panel-default
    .panel-heading
      h4 = category.name
    .panel-body
      table.table.table-striped.snapshot-table
        thead
          tr
            th Attribute
            th Supplied Value
            th.text-center Status
            th.text-center.hidden-print Details
        tbody
          - category.validation_order(@attribute_values).each do |grouping_state, attributes|
            - attributes.each do |attribute, values|
              tr
                td.col-xs-2 = attribute.primary_alias_name
                td.col-xs-9
                  - values.each do |value|
                    .hidden-print
                      - if value
                        pre
                          code
                            = value
                      - else
                        i Not supplied
                    .visible-print-block.word-break
                      - if value
                        = value
                      - else
                        i Not supplied
                    .clearfix

                td.text-center
                  - values.each do |value|
                    - state = AttributeValue.validation_state(category, attribute, value)
                    .hidden-print
                      i class="#{state[:icon_classes].join(' ')}" data-toggle="tooltip" title="#{state[:message]}"
                    .visible-print-block
                      =< state[:state].titleize
                    .clearfix

                td
                  .text-center.hidden-print
                    = link_to documentation_attribute_path(attribute.oid), target: '_blank'
                      i.glyphicon.glyphicon-book

.hidden-print
  - unless @failed
    = link_to snapshot_path(@snapshot, format: 'pdf'), class: 'btn btn-primary' do
      i.glyphicon.glyphicon-download-alt
      | &nbsp;&nbsp; Export as a PDF
    end